
# Data indexes in candle data list
CANDLE_OPEN_TIME_IDX = 0
CANDLE_OPEN_IDX = 1
CANDLE_HIGH_IDX = 2
CANDLE_LOW_IDX = 3
CANDLE_CLOSE_IDX = 4
CANDLE_VOLUME_IDX = 5
CANDLE_CLOSE_TIME_IDX = 6
CANDLE_QUOTE_ASSET_VOL_IDX = 7
CANDLE_NUM_OF_TRADEX_IDX = 8
CANDLE_TAKER_BUY_BASE_ASSET_VOL_IDX = 9
CANDLE_TAKER_BUY_QUOTE_ASSET_VOL_IDX = 10
CANDLE_IGNORE_IDX = 11

CONFIG_FILE = 'config.json'
STATE_FILE = 'state.json'

XMR = 'XMR'
BTC = 'BTC'

INITIAL_BTC = 0.02